-- ClickHouse demo events are loaded from clickhouse/ga4_exports/*.csv.
-- The CSV files match clickhouse/schema.sql insert columns:
--   - event_time is stored as UTC DateTime64(3).
--   - event_date is MATERIALIZED and must not be present in CSV.
--   - ingested_at is generated by ClickHouse default and is omitted from CSV.
-- Use ./scripts/clickhouse-dummy.sh <environment>.
SET date_time_input_format = 'best_effort';
SET input_format_csv_empty_as_default = 1;
SET input_format_defaults_for_omitted_fields = 1;
